### ISSUE TITLE
Login to DJango

### ISSUE THREAD

**Issue by ManPython** [japsu/phpbb-python#1]
Is possible to simplify the solution around to use this in DJango framework around config?
```
INSTALLED_APPS = [
    'phpbb-python.credentials',
    # ...
]
```
https://pypi.org/project/django-openapi/

**Comment by japsu** [comment]
Seems I have neglected to archive this project. As you can see, I have abandoned it more than a decade ago. Please fork it and do with it what you will (within the bounds of the license). I will not be providing further support.
