### ISSUE TITLE
Login to DRF API

### ISSUE THREAD

**Issue by ManPython** [japsu/phpbb-python#2]
Regarding this:
https://github.com/japsu/phpbb-python/issues/1
Also looking option to login to API
https://drf-openapi.readthedocs.io/en/latest/readme.html

**Comment by japsu** [comment]
Seems I have neglected to archive this project. As you can see, I have abandoned it more than a decade ago. Please fork it and do with it what you will (within the bounds of the license). I will not be providing further support.
