### ISSUE TITLE
Login to Jupyter

### ISSUE THREAD

**Issue by ManPython** [japsu/phpbb-python#3]
As last issues.. trying re-activate this.
https://github.com/jupyterlab/jupyterlab/issues/13955

I think, that better can be named this solution as **phpbb-api-python**

**Comment by japsu** [comment]
Seems I have neglected to archive this project. As you can see, I have abandoned it more than a decade ago. Please fork it and do with it what you will (within the bounds of the license). I will not be providing further support.
